const avoidanceData = [
  { building: "Neilson Library", time_block: "8-10 AM", avg_risk: 54, response_count: 34, top_reason: "studying" },
  { building: "Neilson Library", time_block: "10 AM-12 PM", avg_risk: 68, response_count: 46, top_reason: "studying" },
  { building: "Neilson Library", time_block: "12-2 PM", avg_risk: 82, response_count: 61, top_reason: "central traffic" },
  { building: "Neilson Library", time_block: "2-5 PM", avg_risk: 74, response_count: 53, top_reason: "studying" },
  { building: "Neilson Library", time_block: "5-8 PM", avg_risk: 71, response_count: 48, top_reason: "studying" },
  { building: "Neilson Library", time_block: "8-10 PM", avg_risk: 79, response_count: 39, top_reason: "studying" },
  { building: "Campus Center", time_block: "8-10 AM", avg_risk: 43, response_count: 26, top_reason: "coffee" },
  { building: "Campus Center", time_block: "10 AM-12 PM", avg_risk: 63, response_count: 44, top_reason: "mail and food" },
  { building: "Campus Center", time_block: "12-2 PM", avg_risk: 93, response_count: 78, top_reason: "lunch traffic" },
  { building: "Campus Center", time_block: "2-5 PM", avg_risk: 76, response_count: 59, top_reason: "central traffic" },
  { building: "Campus Center", time_block: "5-8 PM", avg_risk: 69, response_count: 41, top_reason: "mail and food" },
  { building: "Campus Center", time_block: "8-10 PM", avg_risk: 45, response_count: 19, top_reason: "central traffic" },
  { building: "Seelye Hall", time_block: "8-10 AM", avg_risk: 66, response_count: 37, top_reason: "class transitions" },
  { building: "Seelye Hall", time_block: "10 AM-12 PM", avg_risk: 79, response_count: 55, top_reason: "class transitions" },
  { building: "Seelye Hall", time_block: "12-2 PM", avg_risk: 74, response_count: 49, top_reason: "class transitions" },
  { building: "Seelye Hall", time_block: "2-5 PM", avg_risk: 67, response_count: 42, top_reason: "class transitions" },
  { building: "Seelye Hall", time_block: "5-8 PM", avg_risk: 36, response_count: 16, top_reason: "central traffic" },
  { building: "Seelye Hall", time_block: "8-10 PM", avg_risk: 18, response_count: 8, top_reason: "central traffic" },
  { building: "Sabin-Reed Hall", time_block: "8-10 AM", avg_risk: 58, response_count: 28, top_reason: "science traffic" },
  { building: "Sabin-Reed Hall", time_block: "10 AM-12 PM", avg_risk: 73, response_count: 36, top_reason: "science traffic" },
  { building: "Sabin-Reed Hall", time_block: "12-2 PM", avg_risk: 69, response_count: 33, top_reason: "class transitions" },
  { building: "Sabin-Reed Hall", time_block: "2-5 PM", avg_risk: 64, response_count: 29, top_reason: "science traffic" },
  { building: "Sabin-Reed Hall", time_block: "5-8 PM", avg_risk: 41, response_count: 17, top_reason: "studying" },
  { building: "Sabin-Reed Hall", time_block: "8-10 PM", avg_risk: 22, response_count: 9, top_reason: "studying" },
  { building: "Ford Hall", time_block: "8-10 AM", avg_risk: 61, response_count: 31, top_reason: "science traffic" },
  { building: "Ford Hall", time_block: "10 AM-12 PM", avg_risk: 76, response_count: 43, top_reason: "class transitions" },
  { building: "Ford Hall", time_block: "12-2 PM", avg_risk: 71, response_count: 37, top_reason: "class transitions" },
  { building: "Ford Hall", time_block: "2-5 PM", avg_risk: 68, response_count: 34, top_reason: "science traffic" },
  { building: "Ford Hall", time_block: "5-8 PM", avg_risk: 39, response_count: 16, top_reason: "studying" },
  { building: "Ford Hall", time_block: "8-10 PM", avg_risk: 21, response_count: 8, top_reason: "studying" },
  { building: "Wright Hall", time_block: "8-10 AM", avg_risk: 63, response_count: 29, top_reason: "class transitions" },
  { building: "Wright Hall", time_block: "10 AM-12 PM", avg_risk: 81, response_count: 47, top_reason: "class transitions" },
  { building: "Wright Hall", time_block: "12-2 PM", avg_risk: 77, response_count: 39, top_reason: "class transitions" },
  { building: "Wright Hall", time_block: "2-5 PM", avg_risk: 66, response_count: 30, top_reason: "class transitions" },
  { building: "Wright Hall", time_block: "5-8 PM", avg_risk: 34, response_count: 14, top_reason: "central traffic" },
  { building: "Wright Hall", time_block: "8-10 PM", avg_risk: 17, response_count: 8, top_reason: "central traffic" },
  { building: "Burton Hall", time_block: "8-10 AM", avg_risk: 55, response_count: 25, top_reason: "science traffic" },
  { building: "Burton Hall", time_block: "10 AM-12 PM", avg_risk: 71, response_count: 32, top_reason: "science traffic" },
  { building: "Burton Hall", time_block: "12-2 PM", avg_risk: 66, response_count: 28, top_reason: "class transitions" },
  { building: "Burton Hall", time_block: "2-5 PM", avg_risk: 62, response_count: 27, top_reason: "science traffic" },
  { building: "Burton Hall", time_block: "5-8 PM", avg_risk: 38, response_count: 15, top_reason: "studying" },
  { building: "Burton Hall", time_block: "8-10 PM", avg_risk: 20, response_count: 8, top_reason: "studying" },
  { building: "Young Science Library", time_block: "8-10 AM", avg_risk: 29, response_count: 12, top_reason: "studying" },
  { building: "Young Science Library", time_block: "10 AM-12 PM", avg_risk: 46, response_count: 18, top_reason: "studying" },
  { building: "Young Science Library", time_block: "12-2 PM", avg_risk: 58, response_count: 23, top_reason: "studying" },
  { building: "Young Science Library", time_block: "2-5 PM", avg_risk: 64, response_count: 27, top_reason: "studying" },
  { building: "Young Science Library", time_block: "5-8 PM", avg_risk: 73, response_count: 31, top_reason: "studying" },
  { building: "Young Science Library", time_block: "8-10 PM", avg_risk: 84, response_count: 29, top_reason: "studying" },
  { building: "Schacht Center", time_block: "8-10 AM", avg_risk: 18, response_count: 9, top_reason: "appointments" },
  { building: "Schacht Center", time_block: "10 AM-12 PM", avg_risk: 27, response_count: 12, top_reason: "appointments" },
  { building: "Schacht Center", time_block: "12-2 PM", avg_risk: 31, response_count: 15, top_reason: "appointments" },
  { building: "Schacht Center", time_block: "2-5 PM", avg_risk: 34, response_count: 17, top_reason: "appointments" },
  { building: "Schacht Center", time_block: "5-8 PM", avg_risk: 24, response_count: 10, top_reason: "appointments" },
  { building: "Schacht Center", time_block: "8-10 PM", avg_risk: 12, response_count: 8, top_reason: "appointments" },
  { building: "Scott Gymnasium", time_block: "8-10 AM", avg_risk: 22, response_count: 10, top_reason: "workouts" },
  { building: "Scott Gymnasium", time_block: "10 AM-12 PM", avg_risk: 28, response_count: 12, top_reason: "workouts" },
  { building: "Scott Gymnasium", time_block: "12-2 PM", avg_risk: 34, response_count: 15, top_reason: "central traffic" },
  { building: "Scott Gymnasium", time_block: "2-5 PM", avg_risk: 48, response_count: 21, top_reason: "workouts" },
  { building: "Scott Gymnasium", time_block: "5-8 PM", avg_risk: 57, response_count: 24, top_reason: "workouts" },
  { building: "Scott Gymnasium", time_block: "8-10 PM", avg_risk: 43, response_count: 18, top_reason: "workouts" },
  { building: "Sage Hall", time_block: "8-10 AM", avg_risk: 14, response_count: 8, top_reason: "rehearsals" },
  { building: "Sage Hall", time_block: "10 AM-12 PM", avg_risk: 21, response_count: 10, top_reason: "rehearsals" },
  { building: "Sage Hall", time_block: "12-2 PM", avg_risk: 26, response_count: 12, top_reason: "central traffic" },
  { building: "Sage Hall", time_block: "2-5 PM", avg_risk: 33, response_count: 15, top_reason: "rehearsals" },
  { building: "Sage Hall", time_block: "5-8 PM", avg_risk: 46, response_count: 19, top_reason: "rehearsals" },
  { building: "Sage Hall", time_block: "8-10 PM", avg_risk: 52, response_count: 17, top_reason: "rehearsals" },
  { building: "Chapin House", time_block: "8-10 AM", avg_risk: 12, response_count: 8, top_reason: "dorm traffic" },
  { building: "Chapin House", time_block: "10 AM-12 PM", avg_risk: 16, response_count: 9, top_reason: "dorm traffic" },
  { building: "Chapin House", time_block: "12-2 PM", avg_risk: 19, response_count: 10, top_reason: "dorm traffic" },
  { building: "Chapin House", time_block: "2-5 PM", avg_risk: 27, response_count: 13, top_reason: "dorm traffic" },
  { building: "Chapin House", time_block: "5-8 PM", avg_risk: 38, response_count: 18, top_reason: "dorm traffic" },
  { building: "Chapin House", time_block: "8-10 PM", avg_risk: 44, response_count: 16, top_reason: "dorm traffic" },
  { building: "Lamont House", time_block: "8-10 AM", avg_risk: 11, response_count: 8, top_reason: "dorm traffic" },
  { building: "Lamont House", time_block: "10 AM-12 PM", avg_risk: 15, response_count: 8, top_reason: "dorm traffic" },
  { building: "Lamont House", time_block: "12-2 PM", avg_risk: 18, response_count: 9, top_reason: "dorm traffic" },
  { building: "Lamont House", time_block: "2-5 PM", avg_risk: 25, response_count: 12, top_reason: "dorm traffic" },
  { building: "Lamont House", time_block: "5-8 PM", avg_risk: 36, response_count: 17, top_reason: "dorm traffic" },
  { building: "Lamont House", time_block: "8-10 PM", avg_risk: 42, response_count: 15, top_reason: "dorm traffic" },
  { building: "Cutter House", time_block: "8-10 AM", avg_risk: 10, response_count: 8, top_reason: "dorm traffic" },
  { building: "Cutter House", time_block: "10 AM-12 PM", avg_risk: 14, response_count: 8, top_reason: "dorm traffic" },
  { building: "Cutter House", time_block: "12-2 PM", avg_risk: 17, response_count: 9, top_reason: "dorm traffic" },
  { building: "Cutter House", time_block: "2-5 PM", avg_risk: 24, response_count: 11, top_reason: "dorm traffic" },
  { building: "Cutter House", time_block: "5-8 PM", avg_risk: 35, response_count: 16, top_reason: "dorm traffic" },
  { building: "Cutter House", time_block: "8-10 PM", avg_risk: 41, response_count: 14, top_reason: "dorm traffic" },
  { building: "Northrop House", time_block: "8-10 AM", avg_risk: 10, response_count: 8, top_reason: "dorm traffic" },
  { building: "Northrop House", time_block: "10 AM-12 PM", avg_risk: 13, response_count: 8, top_reason: "dorm traffic" },
  { building: "Northrop House", time_block: "12-2 PM", avg_risk: 16, response_count: 9, top_reason: "dorm traffic" },
  { building: "Northrop House", time_block: "2-5 PM", avg_risk: 23, response_count: 11, top_reason: "dorm traffic" },
  { building: "Northrop House", time_block: "5-8 PM", avg_risk: 34, response_count: 15, top_reason: "dorm traffic" },
  { building: "Northrop House", time_block: "8-10 PM", avg_risk: 39, response_count: 13, top_reason: "dorm traffic" },
  { building: "John M. Greene Hall", time_block: "8-10 AM", avg_risk: 9, response_count: 8, top_reason: "central traffic" },
  { building: "John M. Greene Hall", time_block: "10 AM-12 PM", avg_risk: 14, response_count: 8, top_reason: "central traffic" },
  { building: "John M. Greene Hall", time_block: "12-2 PM", avg_risk: 22, response_count: 10, top_reason: "central traffic" },
  { building: "John M. Greene Hall", time_block: "2-5 PM", avg_risk: 31, response_count: 13, top_reason: "central traffic" },
  { building: "John M. Greene Hall", time_block: "5-8 PM", avg_risk: 47, response_count: 18, top_reason: "central traffic" },
  { building: "John M. Greene Hall", time_block: "8-10 PM", avg_risk: 58, response_count: 16, top_reason: "rehearsals" },
  { building: "Museum of Art", time_block: "8-10 AM", avg_risk: 8, response_count: 8, top_reason: "central traffic" },
  { building: "Museum of Art", time_block: "10 AM-12 PM", avg_risk: 16, response_count: 9, top_reason: "central traffic" },
  { building: "Museum of Art", time_block: "12-2 PM", avg_risk: 28, response_count: 12, top_reason: "central traffic" },
  { building: "Museum of Art", time_block: "2-5 PM", avg_risk: 35, response_count: 14, top_reason: "central traffic" },
  { building: "Museum of Art", time_block: "5-8 PM", avg_risk: 41, response_count: 16, top_reason: "central traffic" },
  { building: "Museum of Art", time_block: "8-10 PM", avg_risk: 25, response_count: 10, top_reason: "central traffic" },
  { building: "Stoddard Hall", time_block: "8-10 AM", avg_risk: 19, response_count: 9, top_reason: "central traffic" },
  { building: "Stoddard Hall", time_block: "10 AM-12 PM", avg_risk: 27, response_count: 11, top_reason: "central traffic" },
  { building: "Stoddard Hall", time_block: "12-2 PM", avg_risk: 33, response_count: 14, top_reason: "central traffic" },
  { building: "Stoddard Hall", time_block: "2-5 PM", avg_risk: 29, response_count: 12, top_reason: "central traffic" },
  { building: "Stoddard Hall", time_block: "5-8 PM", avg_risk: 17, response_count: 8, top_reason: "central traffic" },
  { building: "Stoddard Hall", time_block: "8-10 PM", avg_risk: 9, response_count: 8, top_reason: "central traffic" }
];
